export default {
  // barlowBold: 'Barlow-Bold',
  // barlowMedium: 'Barlow-Medium',
  // barlowRegular: 'Barlow-Regular',
  // barlowSemiBold: 'Barlow-SemiBold',
  robotoBold: 'Roboto-Bold',
  // robotoMedium: 'Roboto-Medium',
  // robotoRegular: 'Roboto-Regular',
  notoSansCjkKrBlack: 'NotoSansCJKkr-Black',
  notoSansCjkKrBold: 'NotoSansCJKkr-Bold',
  notoSansCjkKrDemilLight: 'NotoSansCJKkr-DemilLight',
  notoSansCjkKrLight: 'NotoSansCJKkr-Light',
  notoSansCjkKrMedium: 'NotoSansCJKkr-Medium',
  notoSansCjkKrRegular: 'NotoSansCJKkr-Regular',
  notoSansCjkKrThin: 'NotoSansCJKkr-Thin',
};
