export default {
  splash: require('../assets/images/splash-hdpi.png'),
  login: require('../assets/images/login-mdpi.png'),
  facebook: require('../assets/images/icon-facebook-mdpi.png'),
  google: require('../assets/images/icon-google-mdpi.png'),
  kakao: require('../assets/images/icon-kakao-mdpi.png'),
  naver: require('../assets/images/icon-naver-mdpi.png'),
  toaping: require('../assets/images/icon-toaping-mdpi.png'),
  back: require('../assets/images/top-back-mdpi.png'),
  hamberger: require('../assets/images/top-hamberger-mdpi.png'),
  camera: require('../assets/images/top-camera-mdpi.png'),
  search: require('../assets/images/search-mdpi.png'),
  tabFriendOn: require('../assets/images/tab_friend_on.png'),
  tabFriendOff: require('../assets/images/tab_friend_off.png'),
  bannerOne: require('../assets/images/bannerOne.png'),
  bannerTwo: require('../assets/images/bannerTwo.png'),
  angleUp: require('../assets/images/angleUp.png'),
  angleDown: require('../assets/images/angleDown.png'),
  event1: require('../assets/images/event1.png'),
  event2: require('../assets/images/event2.png'),
  event1Body: require('../assets/images/event1_body.png'),
  event2Body: require('../assets/images/event2_body.png'),
  like: require('../assets/images/like2.png'),
  talk: require('../assets/images/talk2.png'),
  checkboxOn: require('../assets/images/checkbox_on.png'),
  checkboxOff: require('../assets/images/checkbox_off.png'),
};
