export default {
  // home: 'home',
  // settings: 'settings',
  splash: 'splash',
  tab: 'tab',
  home: 'home',
  login: 'login',
  // tabChat: 'tabChat',
  // tabFind: 'tabFind',
  registerPhoneVerify: 'registerPhoneVerify',
  findIdPassword: 'findIdPassword',
  topMyBooks: 'topMyBooks',
  topNewBooks: 'topNewBooks',
  topActivity: 'topActivity',
  notice: 'notice',
  event: 'event',
  eventDetail: 'eventDetail',
};
