export default {
  splash: 'splash',
  tab: 'tab',
  home: 'home',
  login: 'login',
  registerPhoneVerify: 'registerPhoneVerify',
  findIdPassword: 'findIdPassword',
  topMyBooks: 'topMyBooks',
  topNewBooks: 'topNewBooks',
  topNewBooksDetail: 'topNewBooksDetail',
  topActivity: 'topActivity',
  notice: 'notice',
  event: 'event',
  eventDetail: 'eventDetail',
};
