export default {
  splash: 'splash',
  tab: 'tab',
  home: 'home',
  login: 'login',
  registerPhoneVerify: 'registerPhoneVerify',
  findIdPassword: 'findIdPassword',
  topMyBooks: 'topMyBooks',
  topNewBooks: 'topNewBooks',
  topNewBooksDetail: 'topNewBooksDetail',
  topActivity: 'topActivity',
  notice: 'notice',
  event: 'event',
  eventDetail: 'eventDetail',
  registerForm: 'registerForm',
  registerFormInfo: 'registerFormInfo',
  policy: 'policy',
  intro1: 'intro1',
  intro2: 'intro2',
  intro3: 'intro3',
  toapingLogin: 'toapingLogin',
  cameraRollPicker: 'cameraRollPicker',
  photoEditor: 'photoEditor',
};
